version: '2'

services:
  # note that the app container does NOT remain running - this is on purpose.
  # use the `makefile` to build/run/test the binary as needed
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - 8005:80
    volumes:
      - .:/go/src/github.com/watworks/watworks-public-api
    links:
      - counter-service
    environment:
      COUNTER_SERVICE_URL: http://counter-service:80
  
  counter-service:
    image: watworks/watworks-private-counter-service:0.1.0
    ports:
      - 8006:80
    depends_on:
      - redis
    environment:
      REDIS_URL: redis:6379
  
  redis:
    image: redis:alpine

  docs:
    image: swaggerapi/swagger-ui
    ports:
      - 8003:8080
    environment:
      API_URL: "http://localhost:8006/swagger.json"