version: '2'

services:
  # note that the app container does NOT remain running - this is on purpose.
  # use the `makefile` to build/run/test the binary as needed
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - 8010:80
    volumes:
      - .:/go/src/github.com/watworks/watworks-public-api
    environment:
      APP_CONF_PATH: /go/src/github.com/watworks/watworks-public-api/conf/conf.dev.yml
  
  counter-service:
    image: watworks/watworks-private-counter-service:0.1.0
    ports:
      - 8006:80
    depends_on:
      - redis
    environment:
      REDIS_URL: redis:6379
  
  redis:
    image: redis:alpine