FROM golang:1.8.3-alpine

# need git installed in order to fetch/manage deps w/ `go get`, or the new dep tool
RUN apk --no-cache add git
RUN go get -u github.com/golang/dep/cmd/dep

WORKDIR /go/src/github.com/watworks/watworks-public-api

EXPOSE 80
